%% Step 1 for MOV calculation: This was generated by DeepSeek
% Concatenate and select TS files from Samba_West and Samba_East
% 
% This script extracts temperature and salinity data from Samba moorings
% for the common time period: 11-Sep-2013 to 17-Jul-2017

clear; clc;

%% Define time period (common to both datasets)
t_start = datenum(2013, 9, 11);
t_end = datenum(2017, 7, 17);

%% ========================================================================
% Process Samba_West
% ========================================================================
fprintf('Processing Samba_West...\n');
load('samba_w.mat');

% Select time period
idx_w = find(dt >= t_start & dt < t_end);

% Temperature variables
tem_w = [Temperature_A(:,idx_w), Temperature_AA(:,idx_w), ...
         Temperature_B(:,idx_w), Temperature_BB(:,idx_w), ...
         Temperature_C(:,idx_w), Temperature_CC(:,idx_w), ...
         Temperature_D(:,idx_w)];

% Salinity variables  
sal_w = [Salinity_A(:,idx_w), Salinity_AA(:,idx_w), ...
         Salinity_B(:,idx_w), Salinity_BB(:,idx_w), ...
         Salinity_C(:,idx_w), Salinity_CC(:,idx_w), ...
         Salinity_D(:,idx_w)];

% Metadata
dep_w = [1350, 2902, 3510, 4173, 4558, 4730, 4756];
lon_w = [lon_SAM, lon_Brazil];  % Note: lon_SAM and lon_Brazil from workspace
pres_w = presrange;              % Pressure range from workspace
time_w = dt(idx_w);

% Optional: Bottom pressure (uncomment if needed)
% pr_w = [pres_A(idx_w), pres_AA(idx_w), pres_B(idx_w), ...
%         pres_BB(idx_w), pres_C(idx_w), pres_CC(idx_w), pres_D(idx_w)];

%% ========================================================================
% Process Samba_East
% ========================================================================
fprintf('Processing Samba_East...\n');
load('samba_e.mat');

% Select time period
idx_e = find(dt >= t_start & dt < t_end);

% Temperature variables (P3 and P7 are missing)
tem_e = [Temperature_P1(:,idx_e), Temperature_P2(:,idx_e), ...
         Temperature_P4(:,idx_e), Temperature_P5(:,idx_e), ...
         Temperature_P6(:,idx_e), Temperature_P8(:,idx_e)];

% Salinity variables
sal_e = [Salinity_P1(:,idx_e), Salinity_P2(:,idx_e), ...
         Salinity_P4(:,idx_e), Salinity_P5(:,idx_e), ...
         Salinity_P6(:,idx_e), Salinity_P8(:,idx_e)];

% Metadata
dep_e = [1266, 2129, 4482, 4969, 5185, 4608];
lon_e = [17.5576, 17.3006, 15.0027, 11.2031, 7.4505, 0.0];
pres_e = presrange;              % Pressure range from workspace
time_e = dt(idx_e);

% Optional: Bottom pressure (uncomment if needed)
% pr_e = [pres_P1(idx_e), pres_P2(idx_e), pres_P4(idx_e), ...
%         pres_P5(idx_e), pres_P6(idx_e), pres_P8(idx_e)];

%% ========================================================================
% Clean up workspace (remove unnecessary large variables)
% ========================================================================
clear Temperature_* Salinity_* idx_* dt;

%% ========================================================================
% Save processed data
% ========================================================================
fprintf('Saving data to concat_IESsamba.mat...\n');
save('concat_IESsamba.mat', ...
     'tem_w', 'sal_w', 'dep_w', 'lon_w', 'pres_w', 'time_w', ...
     'tem_e', 'sal_e', 'dep_e', 'lon_e', 'pres_e', 'time_e', ...
     't_start', 't_end', '-v7.3');

fprintf('Done! Data saved successfully.\n');

%% ========================================================================
% Quick summary (optional)
% ========================================================================
fprintf('\nSummary:\n');
fprintf('Samba_West: %d time steps, %d moorings\n', size(tem_w, 2), size(tem_w, 1));
fprintf('Samba_East: %d time steps, %d moorings\n', size(tem_e, 2), size(tem_e, 1));
fprintf('Time period: %s to %s\n', datestr(t_start), datestr(t_end));
